# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-star-ratings
  version: "0.9.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-star-ratings-${{ version }}.tar.gz
  sha256: 7c7f55c1847087b932ca09c2cefb11240510fe384188250d15961024c9c8f2d8

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django
    - django-model-utils
    - django-braces
    - swapper

tests:
  - python:
      imports:
        - star_ratings
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: A Django app to add star ratings to models.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/wildfish/django-star-ratings

extra:
  recipe-maintainers:
    - rxm7706
